# Generated by Django 5.0 on 2023-12-28 13:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Имя')),
                ('email', models.EmailField(blank=True, max_length=250, verbose_name='Email')),
                ('subject', models.TextField(verbose_name='Сообщение')),
                ('date', models.DateTimeField(default=datetime.datetime(2023, 12, 28, 16, 12, 1, 43666), verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Обратная связь',
                'verbose_name_plural': 'Обратная связь',
            },
        ),
    ]
