# Generated by Django 5.0 on 2024-01-31 06:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_alter_feedback_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 31, 9, 24, 15, 744042), verbose_name='Дата публикации'),
        ),
    ]
