# Generated by Django 5.0 on 2024-01-31 09:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_alter_feedback_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 31, 12, 39, 52, 180527), verbose_name='Дата публикации'),
        ),
    ]
