# Generated by Django 5.0 on 2024-02-01 08:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_alter_feedback_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='email',
        ),
        migrations.AddField(
            model_name='feedback',
            name='contacts',
            field=models.TextField(default=1, verbose_name='Контакты для связи'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedback',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 1, 11, 45, 1, 293772), verbose_name='Дата публикации'),
        ),
    ]
