# Generated by Django 5.0 on 2024-02-01 12:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0006_remove_feedback_email_feedback_contacts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 1, 15, 18, 8, 616641), verbose_name='Дата публикации'),
        ),
    ]
