# Generated by Django 5.0 on 2024-02-01 12:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0007_alter_feedback_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 1, 15, 27, 51, 927365), verbose_name='Дата публикации'),
        ),
    ]
