# Generated by Django 5.0 on 2024-02-19 11:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0009_alter_feedback_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 19, 14, 53, 2, 722727), verbose_name='Дата публикации'),
        ),
    ]
