# Generated by Django 5.0 on 2024-06-09 18:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0013_alter_feedback_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 9, 21, 23, 23, 666102), verbose_name='Дата публикации'),
        ),
    ]
