# Generated by Django 5.0 on 2024-02-19 11:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramBotUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Имя')),
                ('chat_id', models.IntegerField(default=0, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2024, 2, 19, 14, 53, 2, 738613), verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Пользователь Telegram Bot',
                'verbose_name_plural': 'Пользователи Telegram Bot',
            },
        ),
    ]
