# Generated by Django 5.0 on 2023-12-28 13:12

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('status', models.BooleanField(choices=[('for_sale', 'на продаже'), ('sales', 'продано')], default='for_sale', max_length=50, verbose_name='Статус')),
                ('type', models.CharField(choices=[('secondary', 'вторичная'), ('new_buildings', 'новостройки'), ('House_and_plots', 'Дом и участки'), ('commercial', 'коммерческая'), ('garages', 'гаражи')], default='new_buildings', max_length=70, verbose_name='Тип недвижимости')),
                ('show', models.BooleanField(default=True, verbose_name='Показывать на сайте?')),
                ('price', models.IntegerField(default=0, verbose_name='Цена')),
                ('bedrooms', models.IntegerField(default=0, verbose_name='Колличество комнат')),
                ('sqft_living', models.IntegerField(default=0, verbose_name='Сколько квадратных метров')),
                ('address', models.CharField(default='', max_length=250, verbose_name='Адрес')),
                ('wall_material', models.CharField(default='', max_length=250, verbose_name='Материал стен')),
                ('the_developer', models.CharField(default='', max_length=250, verbose_name='Застройщик')),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='Широта')),
                ('lon', models.FloatField(blank=True, null=True, verbose_name='Долгота')),
                ('plan', models.ImageField(blank=True, upload_to='media/', verbose_name='Планировка')),
                ('date', models.DateTimeField(default=datetime.datetime(2023, 12, 28, 16, 12, 1, 41671), verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Квартиры',
                'verbose_name_plural': 'Квартиры',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='media/', verbose_name='Изображение')),
                ('apartment', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.apartments')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображение',
            },
        ),
    ]
