# Generated by Django 5.0 on 2023-12-28 13:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartments',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 28, 16, 36, 1, 375518), verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='apartments',
            name='status',
            field=models.CharField(choices=[('for_sale', 'на продаже'), ('sales', 'продано')], default='for_sale', max_length=50, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='apartments',
            name='the_developer',
            field=models.CharField(blank=True, max_length=250, verbose_name='Застройщик'),
        ),
        migrations.AlterField(
            model_name='apartments',
            name='wall_material',
            field=models.CharField(blank=True, max_length=250, verbose_name='Материал стен'),
        ),
    ]
