# Generated by Django 5.0 on 2024-01-31 06:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_apartments_date_alter_apartments_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartments',
            name='floor',
            field=models.IntegerField(blank=True, default=1, verbose_name='Этаж'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apartments',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 31, 9, 24, 15, 742998), verbose_name='Дата публикации'),
        ),
    ]
