# Generated by Django 5.0 on 2024-02-01 08:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_apartments_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartments',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 1, 11, 45, 1, 292672), verbose_name='Дата публикации'),
        ),
    ]
