# Generated by Django 5.0 on 2024-02-19 08:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_apartments_date_alter_apartments_show_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apartments',
            options={'verbose_name': 'Квартиру', 'verbose_name_plural': 'Квартиры'},
        ),
        migrations.AlterField(
            model_name='apartments',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 19, 11, 23, 10, 253123), verbose_name='Дата публикации'),
        ),
    ]
