# Generated by Django 5.0 on 2024-06-09 16:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_apartments_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartments',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='apartments',
            name='bedrooms',
            field=models.IntegerField(default=1, verbose_name='Колличество комнат'),
        ),
        migrations.AlterField(
            model_name='apartments',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 9, 19, 51, 9, 201913), verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='apartments',
            name='price',
            field=models.IntegerField(default=1, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='apartments',
            name='sqft_living',
            field=models.FloatField(default=1, verbose_name='Сколько квадратных метров'),
        ),
        migrations.AlterField(
            model_name='apartments',
            name='the_developer',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Застройщик'),
        ),
        migrations.AlterField(
            model_name='apartments',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='apartments',
            name='wall_material',
            field=models.CharField(max_length=500, verbose_name='Материал стен'),
        ),
    ]
