# Generated by Django 5.0 on 2024-06-09 16:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_alter_apartments_address_alter_apartments_bedrooms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartments',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 9, 19, 56, 27, 290772), verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='apartments',
            name='floor',
            field=models.IntegerField(default=1, verbose_name='Этаж'),
        ),
        migrations.AlterField(
            model_name='apartments',
            name='wall_material',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Материал стен'),
        ),
    ]
