# Generated by Django 5.0 on 2024-06-09 16:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_alter_apartments_date_alter_apartments_floor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartments',
            name='address',
            field=models.CharField(default='', max_length=500, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='apartments',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 9, 19, 57, 41, 306496), verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='apartments',
            name='the_developer',
            field=models.CharField(default='', max_length=500, verbose_name='Застройщик'),
        ),
        migrations.AlterField(
            model_name='apartments',
            name='wall_material',
            field=models.CharField(default='', max_length=500, verbose_name='Материал стен'),
        ),
    ]
