# Generated by Django 5.0 on 2024-06-09 18:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_alter_apartments_address_alter_apartments_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartments',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 9, 21, 23, 23, 665102), verbose_name='Дата публикации'),
        ),
    ]
