# Generated by Django 5.0 on 2024-06-09 18:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_alter_apartments_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartments',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 9, 21, 34, 24, 418318), verbose_name='Дата публикации'),
        ),
    ]
