# Generated by Django 5.0 on 2024-01-31 06:24

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalApartments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('status', models.CharField(choices=[('for_sale', 'на продаже'), ('sales', 'продано')], default='for_sale', max_length=50, verbose_name='Статус')),
                ('type', models.CharField(choices=[('secondary', 'вторичная'), ('new_buildings', 'новостройки')], default='secondary', max_length=70, verbose_name='Тип недвижимости')),
                ('show', models.BooleanField(default=True, verbose_name='Показывать на сайте?')),
                ('price', models.IntegerField(default=0, verbose_name='Цена')),
                ('bedrooms', models.IntegerField(default=0, verbose_name='Колличество комнат')),
                ('floor', models.IntegerField(blank=True, verbose_name='Этаж')),
                ('sqft_living', models.IntegerField(default=0, verbose_name='Сколько квадратных метров')),
                ('address', models.CharField(default='', max_length=250, verbose_name='Адрес')),
                ('wall_material', models.CharField(blank=True, max_length=250, verbose_name='Материал стен')),
                ('the_developer', models.CharField(blank=True, max_length=250, verbose_name='Застройщик')),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='Широта')),
                ('lon', models.FloatField(blank=True, null=True, verbose_name='Долгота')),
                ('plan', models.ImageField(blank=True, upload_to='media/', verbose_name='Планировка')),
                ('date', models.DateTimeField(default=datetime.datetime(2024, 1, 31, 9, 24, 15, 745039), verbose_name='Дата публикации')),
                ('contacts', models.TextField(verbose_name='Контакты для связи')),
            ],
            options={
                'verbose_name': 'Квартира внешнего клиента',
                'verbose_name_plural': 'Квартиры внешних клиентов',
            },
        ),
        migrations.CreateModel(
            name='ExternalApartmentsImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='media/', verbose_name='Изображение')),
                ('apartment', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='external_apartments_images', to='sale.externalapartments')),
            ],
            options={
                'verbose_name': 'Изображение внешнего клиента',
                'verbose_name_plural': 'Изображение внешних клиентов',
            },
        ),
    ]
