# Generated by Django 5.0 on 2024-01-31 06:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalapartments',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 31, 9, 53, 22, 610358), verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='externalapartments',
            name='sqft_living',
            field=models.FloatField(default=0, verbose_name='Сколько квадратных метров'),
        ),
    ]
