# Generated by Django 5.0 on 2024-01-31 09:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_alter_externalapartments_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalapartments',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 31, 12, 39, 52, 181057), verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='externalapartments',
            name='show',
            field=models.BooleanField(default=False, verbose_name='Показывать на сайте?'),
        ),
    ]
