# Generated by Django 5.0 on 2024-02-01 08:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0003_alter_externalapartments_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalapartments',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 1, 11, 45, 1, 294797), verbose_name='Дата публикации'),
        ),
    ]
