# Generated by Django 5.0 on 2024-02-01 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0005_remove_externalapartments_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalapartments',
            name='external',
            field=models.BooleanField(default=False, verbose_name='Создано внешними клиентами?'),
        ),
    ]
