# Generated by Django 5.0 on 2024-02-19 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0006_externalapartments_external'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='externalapartments',
            options={'verbose_name': 'Квартиру', 'verbose_name_plural': 'Квартиры'},
        ),
    ]
