# Generated by Django 5.0 on 2024-06-09 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0007_alter_externalapartments_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalapartments',
            name='contacts',
            field=models.TextField(blank=True, verbose_name='Контакты для связи'),
        ),
    ]
